openapi: 3.2.0
info:
  title: Dropbox API Reference Users API
  description: 'The powerful, yet simple, Dropbox API allows you to manage and control content and team settings programmatically and extend Dropbox capabilities in new and powerful ways. This is a collection that includes requests to all endpoints in the Dropbox API.


    The Dropbox API is divided in two groups of endpoints: User Endpoints and Business Endpoints. Operations that would most likely be executed by a user, such as file operations, are in the User Endpoints folder. Operations that would most likely be executed by a team administrator, such as adding users to groups, live in the Business Endpoints folder.


    If you are new to Dropbox Business and Team Administration, please have a look at the Dropobox Admin Guide.


    If you want more information on how to use our API please refer to our Developer Portal.


    # What''s in the collection?


    The endpoints are organized in the following folders:

    * account

    * auth

    * check

    * contacts

    * file_properties

    * file_requests

    * files

    * sharing

    * team

    * team_log

    * users


    # Authorization


    ## OAuth 2.0 for API Access

    Dropbox uses OAuth 2.0, an open specification, to authorize access to data. To get an OAuth token from Dropbox to enable Postman to access your Dropbox account via the API you’ll need to create a new app on the DBX Platform.


    ## Creating an App on the DBX Platform

    Navigate to https://www.dropbox.com/developers/apps and select “Create app”

    1. Choose an API

    2. Choose the type of access you need

    3. Give your app a name

    4. Choose the Dropbox account that will own your app


    For reference, please use the Dropbox OAuth guide


    ## Generating an Access Token

    Once you select “Create app” a page will load that displays information about your newly created app. To generate an access token scroll down to “OAuth 2” and click “Generate” beneath “Generated access token.” The token will display as a long string of characters. Copy this token for use with the Postman Collection.


    ## Adding an Access Token to the requests

    In the Postman client, click on the three dots to the right of the collection name to "View more actions."


    !Screenshot of adding access token


    Then, click "Edit."


    Click on the "Variables" tab and, in the row for the `access_token` variable, paste your access token in the `CURRENT VALUE` column. The default value is `your-access-token-here`.


    !Screenshot of adding access token


    For information on sessions and variables in Postman see the blog post at https://blog.postman.com/sessions-faq/.


    # Notes

    * Dropbox also has a Postman Collection in the API Network to help administrators with team management workflows. It is called Dropbox Team Admin Workflows.'
  version: 1.0.0
servers:
- url: https://api.dropbox.com
security:
- bearerAuth: []
tags:
- name: Users
  description: This namespace contains endpoints and data types for user management.
paths:
  /2/users/features/get_values:
    post:
      tags:
      - Users
      summary: Dropbox features/get_values
      description: 'features/get_values


        scope: `account_info.read`


        Get a list of feature values that may be configured for the current account.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"features\": [\n        {\n            \".tag\": \"paper_as_files\"\n        }, \n        {\n            \".tag\": \"file_locking\"\n        }\n    ]\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                values:
                - .tag: paper_as_files
                  paper_as_files:
                    .tag: enabled
                    enabled: true
      operationId: post2UsersFeaturesGetValues
      x-operation-id-source: derived
  /2/users/get_account:
    post:
      tags:
      - Users
      summary: Dropbox get_account
      description: 'get_account


        scope: `sharing.read`


        Get information about a user''s account.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"account_id\": \"dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc\"\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                account_id: dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc
                name:
                  given_name: Franz
                  surname: Ferdinand
                  familiar_name: Franz
                  display_name: Franz Ferdinand (Personal)
                  abbreviated_name: FF
                email: franz@dropbox.com
                email_verified: true
                disabled: false
                is_teammate: false
                profile_photo_url: https://dl-web.dropbox.com/account_photo/get/dbaphid%3AAAHWGmIXV3sUuOmBfTz0wPsiqHUpBWvv3ZA?vers=1556069330102&size=128x128
      operationId: post2UsersGetAccount
      x-operation-id-source: derived
  /2/users/get_account_batch:
    post:
      tags:
      - Users
      summary: Dropbox get_account_batch
      description: 'get_account_batch


        scope: `sharing.read`


        Get information about multiple user accounts. At most 300 accounts may be queried per request.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"account_ids\": [\n        \"dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc\", \n        \"dbid:AAH1Vcz-DVoRDeixtr_OA8oUGgiqhs4XPOQ\"\n    ]\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
              - account_id: dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc
                name:
                  given_name: Franz
                  surname: Ferdinand
                  familiar_name: Franz
                  display_name: Franz Ferdinand (Personal)
                  abbreviated_name: FF
                email: franz@dropbox.com
                email_verified: true
                disabled: false
                is_teammate: false
                profile_photo_url: https://dl-web.dropbox.com/account_photo/get/dbaphid%3AAAHWGmIXV3sUuOmBfTz0wPsiqHUpBWvv3ZA?vers=1556069330102&size=128x128
      operationId: post2UsersGetAccountBatch
      x-operation-id-source: derived
  /2/users/get_current_account:
    post:
      tags:
      - Users
      summary: Dropbox get_current_account
      description: 'get_current_account


        scope: `account_info.read`


        Get information about the current user''s account.'
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                account_id: dbid:AAH4f99T0taONIb-OurWxbNQ6ywGRopQngc
                name:
                  given_name: Franz
                  surname: Ferdinand
                  familiar_name: Franz
                  display_name: Franz Ferdinand (Personal)
                  abbreviated_name: FF
                email: franz@dropbox.com
                email_verified: true
                disabled: false
                locale: en
                referral_link: https://db.tt/ZITNuhtI
                is_paired: true
                account_type:
                  .tag: business
                root_info:
                  .tag: user
                  root_namespace_id: '3235641'
                  home_namespace_id: '3235641'
                country: US
                team:
                  id: dbtid:AAFdgehTzw7WlXhZJsbGCLePe8RvQGYDr-I
                  name: Acme, Inc.
                  sharing_policies:
                    shared_folder_member_policy:
                      .tag: team
                    shared_folder_join_policy:
                      .tag: from_anyone
                    shared_link_create_policy:
                      .tag: team_only
                  office_addin_policy:
                    .tag: disabled
                team_member_id: dbmid:AAHhy7WsR0x-u4ZCqiDl5Fz5zvuL3kmspwU
      operationId: post2UsersGetCurrentAccount
      x-operation-id-source: derived
  /2/users/get_space_usage:
    post:
      tags:
      - Users
      summary: Dropbox get_space_usage
      description: 'get_space_usage


        scope: `account_info.read`


        Get the space usage information for the current user''s account.'
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                used: 314159265
                allocation:
                  .tag: individual
                  allocated: 10000000000
      operationId: post2UsersGetSpaceUsage
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
