openapi: 3.2.0
info:
  title: Dropbox API Reference Team > Member_space_limits API
  description: The powerful, yet simple, Dropbox API allows you to manage and control content and team settings programmatically and extend Dropbox capabilities in new and powerful ways.
  version: 1.0.0
servers:
- url: https://api.dropbox.com
security:
- bearerAuth: []
tags:
- name: Team > Member_space_limits
paths:
  /2/team/member_space_limits/excluded_users/add:
    post:
      tags:
      - Team > Member_space_limits
      summary: Dropbox member_space_limits/excluded_users/add
      description: 'member_space_limits/excluded_users/add


        scope: `members.write`


        Add users to member space limits excluded users list.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"users\": [\n        {\n            \".tag\": \"team_member_id\", \n            \"team_member_id\": \"dbmid:efgh5678\"\n        }\n    ]\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                status:
                  .tag: success
      operationId: post2TeamMemberSpaceLimitsExcludedUsersAdd
      x-operation-id-source: derived
  /2/team/member_space_limits/excluded_users/list:
    post:
      tags:
      - Team > Member_space_limits
      summary: Dropbox member_space_limits/excluded_users/list
      description: 'member_space_limits/excluded_users/list


        scope: `members.read`


        List member space limits excluded users.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"limit\": 100\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                users: []
                has_more: false
                cursor: ZtkX9_EHj3x7PMkVuFIhwKYXEpwpLwyxp9vMKomUhllil9q7eWiAu
      operationId: post2TeamMemberSpaceLimitsExcludedUsersList
      x-operation-id-source: derived
  /2/team/member_space_limits/excluded_users/list/continue:
    post:
      tags:
      - Team > Member_space_limits
      summary: Dropbox member_space_limits/excluded_users/list/continue
      description: 'member_space_limits/excluded_users/list/continue


        scope: `members.read`


        Continue listing member space limits excluded users.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"cursor\": \"ZtkX9_EHj3x7PMkVuFIhwKYXEpwpLwyxp9vMKomUhllil9q7eWiAu\"\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                users: []
                has_more: false
                cursor: ZtkX9_EHj3x7PMkVuFIhwKYXEpwpLwyxp9vMKomUhllil9q7eWiAu
      operationId: post2TeamMemberSpaceLimitsExcludedUsersListContinue
      x-operation-id-source: derived
  /2/team/member_space_limits/excluded_users/remove:
    post:
      tags:
      - Team > Member_space_limits
      summary: Dropbox member_space_limits/excluded_users/remove
      description: 'member_space_limits/excluded_users/remove


        scope: `members.write`


        Remove users from member space limits excluded users list.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"users\": [\n        {\n            \".tag\": \"team_member_id\", \n            \"team_member_id\": \"dbmid:efgh5678\"\n        }\n    ]\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                status:
                  .tag: success
      operationId: post2TeamMemberSpaceLimitsExcludedUsersRemove
      x-operation-id-source: derived
  /2/team/member_space_limits/get_custom_quota:
    post:
      tags:
      - Team > Member_space_limits
      summary: Dropbox member_space_limits/get_custom_quota
      description: 'member_space_limits/get_custom_quota


        scope: `members.read`


        Get users custom quota. Returns none as the custom quota if none was set. A maximum of 1000 members can be specified in a single call.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"users\": [\n        {\n            \".tag\": \"team_member_id\", \n            \"team_member_id\": \"dbmid:efgh5678\"\n        }\n    ]\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
              - .tag: other
      operationId: post2TeamMemberSpaceLimitsGetCustomQuota
      x-operation-id-source: derived
  /2/team/member_space_limits/remove_custom_quota:
    post:
      tags:
      - Team > Member_space_limits
      summary: Dropbox member_space_limits/remove_custom_quota
      description: 'member_space_limits/remove_custom_quota


        scope: `members.write`


        Remove users custom quota. A maximum of 1000 members can be specified in a single call.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"users\": [\n        {\n            \".tag\": \"team_member_id\", \n            \"team_member_id\": \"dbmid:efgh5678\"\n        }\n    ]\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
              - .tag: other
      operationId: post2TeamMemberSpaceLimitsRemoveCustomQuota
      x-operation-id-source: derived
  /2/team/member_space_limits/set_custom_quota:
    post:
      tags:
      - Team > Member_space_limits
      summary: Dropbox member_space_limits/set_custom_quota
      description: 'member_space_limits/set_custom_quota


        scope: `members.read`


        Set users custom quota. Custom quota has to be at least 15GB. A maximum of 1000 members can be specified in a single call.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"users_and_quotas\": [\n        {\n            \"user\": {\n                \".tag\": \"team_member_id\", \n                \"team_member_id\": \"dbmid:efgh5678\"\n            }, \n            \"quota_gb\": 30\n        }\n    ]\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            X-Dropbox-Request-Id:
              schema:
                type: integer
                example: '1234'
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
              - .tag: other
      operationId: post2TeamMemberSpaceLimitsSetCustomQuota
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
